### ISSUE TITLE
Define the restaurant entity

### ISSUE THREAD

**Issue by chininchu** [chininchu/Dining-Review-API#5]
Our restaurant dining review app scenario revolves around the following basic concepts:

- a restaurant
- a dining review
- a user

A restaurant will have a set of review scores based on those submitted by users. On a scale of 1 to 5, with 5 being the best, a restaurant will have individual scores for the following food allergies:

- [x] peanut
- [x] egg
- [x] dairy

- [x] Each individual score will be the average across all the submitted scores for that given category. In the absence of any submitted score, an individual category score will have a null value.

- [x] A restaurant will also have an overall score, which will be the average across all the submitted scores across all the categories. A user can later search for restaurants based on these scores.

- [x] Define a plain ol’ Java object (POJO) class to represent a restaurant. Be sure to include the property that represents the unique database id, which you can define as type Long.

**Comment by chininchu** [comment]
Hi Jason, I would assume that the creation averages for any kind of scores is usually done within the Controllers correct?. Why is the instruction asking us to calculate the average within the data model?.

**Comment by JMComstock** [comment]
It is generally preferable to perform these calculations within the data model rather than the controllers. Let me explain the reasons behind this recommendation:

Separation of Concerns: In the Model-View-Controller (MVC) design pattern, each component has a specific role. The data model is responsible for managing the data and its behavior, while the controllers handle user input and interact with the model and view. By calculating averages within the data model, you keep the concerns of data manipulation and business logic separate from the user interface interactions.

Code Reusability: If the average calculation logic is placed in the data model, it becomes easily accessible to any part of the application that needs it. This promotes code reusability and maintainability, as you can use the same logic across different controllers or even in other parts of the application.

Consistency and Accuracy: By centralizing the calculation in the data model, you ensure that all controllers that access the average calculation will produce consistent results. This helps avoid discrepancies or inconsistencies that may arise from implementing the logic in multiple places.

Testing: Placing the average calculation in the data model facilitates easier unit testing. You can write test cases specifically for the data model to verify the correctness of the average calculation without needing to test the user interface or controllers.

Abstraction: The data model is usually designed to abstract away the underlying data storage and retrieval details. By placing the average calculation in the data model, you can perform the calculation regardless of where the data is coming from, whether it's from a database, a file, or any other source.

However, it's important to note that this is a general guideline and not a strict rule. In some cases, depending on the complexity of the application and specific requirements, it might make sense to perform certain calculations within the controllers. The key is to maintain a clear separation of concerns and ensure that the application remains organized, maintainable, and scalable.

**Comment by chininchu** [comment]
Thank you so much for such a well defined explanation. I will keep the ticket open just incase if I run into any problems. Thanks.
